### PR TITLE
[bugfix] Fix incorrect package name extraction for nested messages

### LINKED ISSUE #20: Incorrect Package Name Parsing
## Issue
The `package_from_name/1` method in `Builder.Util` currently extracts an incorrect package name when given a nested message name.

For example:
```
>  Util.package_from_name("testServiceV3.TestRequest.Payload")
"testServiceV3.TestRequest"
```
It's supposed to return:  `testServiceV3`

## Cause

Unlike `protoc-gen-golang` that retains file package info in a `.pb.go` FileDescriptorProto, `protoc-gen-elixir` builds a DescriptorProto in `.pb.ex`, losing the original package name and options from the `.proto`.

No clear way at present to parse correct package name.

## Proposal

Potential options:

- Refine `protoc-gen-elixir` to retain packages - but costly
- Build utility to correctly set package name after compile

### PR DESCRIPTION
**Pull request by zhihuizhang17**
## Summary
The `package_from_name/1` method in `Builder.Util` currently extracts an incorrect package name when given a nested message name.

For example:
```
>  Util.package_from_name("testServiceV3.TestRequest.Payload")
"testServiceV3.TestRequest"
```
It's supposed to return:  `testServiceV3`

This PR fixes the issue by keeping only the outermost module component as the package name for any nested message input.

fixes #20

### CODE REVIEW

File: lib/grpc_reflection/service/builder/util.ex [hunk 1]
```diff
@@ -7,13 +7,35 @@ defmodule GrpcReflection.Service.Builder.Util do
...
+    if function_exported?(module, :descriptor, 0) do
+      parent_symbol = symbol |> String.split(".") |> Enum.slice(0..-2) |> Enum.join(".")
+
+      case module.descriptor() do
+        %Google.Protobuf.ServiceDescriptorProto{} -> parent_symbol
+        _ -> handle_parent_module(module, parent_symbol)
+      end
+    else
+      symbol
+    end
```
Comment (mjheilmann) [inline lib/grpc_reflection/service/builder/util.ex:20]: Some of this logic is unnecessary.  Since we know that a package name can't be a service nor a type, we can infer that one of the following is true:
1. The module name that matches the package name will not be an actual module
2. If the package name overlaps with a module name, it shouldn't export `descriptor/0`

Possible alternate implementation:

```elixir
def get_package(symbol) do
  parent_symbol = symbol |> String.split(".") |> Enum.slice(0..-2) |> Enum.join(".")
  parent_module = try_get_parent_module(parent_symbol)
  if function_exported?(parent_module, :descriptor, 0) do
    get_package(parent_symbol)
  else
    parent_symbol
  end
end
```

File: lib/grpc_reflection/service/builder/util.ex [hunk 2]
```diff
@@ -7,13 +7,35 @@ defmodule GrpcReflection.Service.Builder.Util do
...
+
+  defp try_get_parent_module(module) do
+    try do
+      module
+      |> Module.split()
+      |> Enum.slice(0..-2)
+      |> Module.safe_concat()
+    rescue
+      _ -> nil
+    end
```
Comment (mjheilmann) [inline lib/grpc_reflection/service/builder/util.ex:38]: This looks like it does a similar thing to `Util.convert_symbol_to_module`.  Since you are calculating the parent_symbol directly, maybe we should call `convert_symbol_to_module` while updating `convert_symbol_to_module` to also use `Module.safe_concat`.

The `rescue` would need to be in `get_package` however as we still want to crash if we cannot locate types while processing services

Comment (zhihuizhang17) [reply lib/grpc_reflection/service/builder/util.ex]: Nice catch.

File: lib/grpc_reflection/service/builder/util.ex (hunk 1 above)
Comment (zhihuizhang17) [reply lib/grpc_reflection/service/builder/util.ex]: Sure, updated.

**Review by mjheilmann — APPROVED** [review]
